/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BookGroup: typeof import('./src/components/BookGroup.vue')['default']
    GrammarList: typeof import('./src/components/GrammarList.vue')['default']
    PageButton: typeof import('./src/components/PageButton.vue')['default']
    PreviewModal: typeof import('./src/components/PreviewModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    ViewSection: typeof import('./src/components/ViewSection.vue')['default']
  }
}
